### ISSUE TITLE
.gitignore schreiben

### ISSUE THREAD

**Issue by Supergecki** [Supergecki/LaTriX#1]
Es muss eine .gitignore-Datei für den Gebrauch im C#-Projekt geschrieben werden. Vorerst sollte es ausreichen, dabei kompilierte Dateien/Binaries auszuschließen.

**Comment by Anasalzoabi** [comment]
Bitte fügen Sie in der Datei (.gitignore) .vs/ und .vscode/ hinzu, um automatisch generierte Dateien von Visual Studio und Visual Studio Code zu ignorieren.

**Comment by Supergecki** [comment]
Das ist ein berechtigter Einwand, ich kümmere mich darum.
