### ISSUE TITLE
Release inkl. Executable erstellen

### ISSUE THREAD

**Issue by Supergecki** [Supergecki/LaTriX#12]
Ganz zum Schluss muss ein Release erstellt werden, der im besten Fall auch eine entsprechende ausführbare Datei enthält. Mit dieser sollte ein nichtinformatischer Anwender die GUI "out of the box" installieren und nutzen können. Wenn alle Roadmap-Features implementiert sind, markiert diese Version v1.0

**Comment by Supergecki** [comment]
Ich habe mich mal kurz belesen, wir würden ja sicherlich gern eine Standalone-Executable haben wollen (sodass man einfach eine ".exe"-Datei downloaden und dann ausführen kann, ohne irgendwelche anderen Dateien dafür zu brauchen). In der Dokumentation steht folgendes dazu: https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli

Ich hab das mal ausprobiert, es scheint zu reichen, wenn man folgende Zeile in die Projekt-Datei der GUI innerhalb von `<PropertyGroup>` einfügt:
```xml
<PublishSingleFile>true</PublishSingleFile>
```

Dann lässt sich
```shell
dotnet publish
```
in der Kommandozeile ausführen. Dann findet man im Verzeichnis `src/GUI/bin/Release/win-x64/publish` die Datei `LaTriX.exe`. Die müssten wir in unseren Release als Binary einfügen. Sag mal Bescheid, ob das so klappt oder du Alternativlösungen findest.

**Comment by Supergecki** [comment]
Bitte erst #31 bearbeiten!

**Comment by Supergecki** [comment]
> Ich habe mich mal kurz belesen, wir würden ja sicherlich gern eine Standalone-Executable haben wollen (sodass man einfach eine ".exe"-Datei downloaden und dann ausführen kann, ohne irgendwelche anderen Dateien dafür zu brauchen). In der Dokumentation steht folgendes dazu: https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli
> 
> Ich hab das mal ausprobiert, es scheint zu reichen, wenn man folgende Zeile in die Projekt-Datei der GUI innerhalb von `<PropertyGroup>` einfügt:
> 
> ```
> <PublishSingleFile>true</PublishSingleFile>
> ```
> 
> Dann lässt sich
> 
> ```shell
> dotnet publish
> ```
> 
> in der Kommandozeile ausführen. Dann findet man im Verzeichnis `src/GUI/bin/Release/win-x64/publish` die Datei `LaTriX.exe`. Die müssten wir in unseren Release als Binary einfügen. Sag mal Bescheid, ob das so klappt oder du Alternativlösungen findest.

Hab's ausprobiert und versucht, die Standalone-Executable auf einem bisher an der Entwicklung unbeteiligten Gerät auszuführen, es funktioniert! Wenn wir diesen Weg umsetzen und vorher noch #31 bearbeiten, steht dem Release nichts mehr im Weg.

**Comment by Anasalzoabi** [comment]
Ich habe das Release hochgeladen und die Version auf v1.1 geändert, da ich mehrere wichtige Änderungen und Verbesserungen vorgenommen habe. Details dazu findest du in [diesem Commit](https://github.com/Supergecki/LaTriX/pull/28/commits/31d798a66de7c4fd70bc3212b2b84d4d8fc1b942). Diese Änderungen umfassen unter anderem Optimierungen der GUI und die Hinzufügung von zusätzlichem Exception-Handling, um die Stabilität der Anwendung zu verbessern.
