### ISSUE TITLE
Verändertes Klassendesign der GUI in UML festhalten

### ISSUE THREAD

**Issue by Supergecki** [Supergecki/LaTriX#2]
Es muss ein Klassendiagramm in UML erstellt werden, in dem alle Klassen des Projekts in ihrer Planung aufgezeigt werden. Dabei gibt es einerseits die Klassen in der Klassenbibliothek, die aus den integrierten Tests und wiederum die aus der GUI.

**Comment by Supergecki** [comment]
Ich hätte hier einen Vorschlag: ![include](https://www.plantuml.com/plantuml/png/dL51QiCm4Bph5JecbFp0c9GSIY61GDsIwzPPN55PCYlP54h_tjKcKjCab19yyCxCpcYGbY42nR6tQe3s7JhKQsZ8xDRcLNsgra88YS7Tohi9AI8nVQUhYdtHj7MjGoJZEdtKDy3me_7YcHrGrTIwbsd-b_K5s-WfMmyeMIUPvkgBlykM3OOOIjM4hjITlDcBzk-MnN5xkOVdnzBhVXYa2FzdQRcmJszehKWPdEWRC6xBWQ9dy4iVpPPyHz2VlOf8dAXNX13nYCIg4hrOr3-dvq7OSkP9U5vNMHJYx9uv-VBshoqkqUt7tdu3)

LaTriXGUI ist dabei erst einmal etwas rudimentär gehalten, da die genauen Methoden der darin enthaltenen Klassen später von der exakten GUI-Implementierung abhängen. Sobald dort genauere Informationen vorliegen, können z.B. entsprechende Eventhandler eingefügt werden.
Wäre das so in Ordnung? Bitte um Rückmeldung @Anasalzoabi

**Comment by Anasalzoabi** [comment]
Ja, das sieht gut aus. Die Struktur ist klar und leicht nachvollziehbar. Danke für die Erstellung

**Comment by Supergecki** [comment]
Ich habe ein paar erklärende Worte zum Diagramm auf eine eigene Wiki-Seite geschrieben. Alle Dokumentationen zum Klassendesign sollten nun dort festgehalten werden.

**Comment by Supergecki** [comment]
![include](https://www.plantuml.com/plantuml/png/ZL3HQW8n47o_hyYZKkqNs4FnGGeAGg_5r_JSdg59JZPxKX3_lTbSBurSACK7TsVcPZQpT2IHEgEBiwm_PGDYAojKXwrwBwv5hQLpZC1XtTeB805w-460xOnOQTLO0vR4LSC7pKJjPy2PGDMSwEPbYuMt9rMNfN24oZRYnsOd_VfLjS5wKPMJ7l2JC66Q9Uvoc9uYzjX7JV_AU8EQMamoUe0pBc7wRyOypQXF4iK6AChM7fXaZAR5pV_6jLRWoCLkUSlqUsdLCN2vlaPbJTClSgyVFJrxtERrETwrEf_v4FwVi3YYBoVGcgcu9FnEAhltXip7vOxlr1xR1gLXITehKzvHh14a0Mz3TC7mV5x-fWz3G6DcOZx8Yu4Cm7tFx3nkFoTSWZrsHdy3)

Ich habe für die etwas elegantere Lösung von #5 und #6 eine kleine Änderung am Klassendesign vorgenommen. Dadurch ist die Konversion flexibel, was das Spaltenalignment der LaTeX-Matrix anbelangt (und muss nicht automatisch mit zentrierten Spalten arbeiten). Ich warte auf eine kurze Rückmeldung, ob das in deinem Sinne ist.

**Comment by Anasalzoabi** [comment]
das sieht sehr gut und strukturiert aus. Ich finde die Änderungen sinnvoll, da sie die Freiheit bieten, sowohl Spalten als auch Zeilen flexibel zu gestalten. Danke

**Comment by Supergecki** [comment]
Die Testklasse fiel doch deutlich komplexer aus, als im ursprünglichen Entwurf geplant. Grund dafür ist unter anderem, dass sich die Implementierung einer generischen Testmethode (die also verschiedene Matrix-Datentypen verwenden kann) als relativ schwierig erwies und daher in zwei Einzelmethoden, eine für Double-Matrizen, eine für Float-Matrizen, aufgeteilt wurde. Außerdem musste für das Testen des Alignment-Parameters ebenfalls noch eine Methode erschaffen werden. Diese Abweichungen vom Ursprungsentwurf müssen noch im UML-Diagramm dokumentiert werden, das würde ich demnächst noch übernehmen.

**Comment by Supergecki** [comment]
![include](https://www.plantuml.com/plantuml/png/lLLVRzem47_Ffx2q5z20Jq1HAxgXIbIgD3PLgYfaaYjuSspaEAmLwtVV7TSuQUEnyD2A1-v-z-TtVynnNdZfV9dhP2lJNt8DOYuNJjtErIhP9wcMHK48t4wjsO7pu13-BC2KkRZGQcroC5xiDJpuWKXH1ZSGJgqt_hbo-m6fjsxnj0MnJwqkSuCUzZVPnsEazogTJ4JXdJ9hyK9pBL5zNDW3zNWnwJ60aiWFqg31BYlfB60ZBgL_Z8FhQd0mG1oxWzIDOz1ia0EN7kMp6Xvns_rasAmctKWdPk13mYa2lGXbFtd6Jtj12oXyWUkGAsnCfbxmkWY-b5xEm82JtjB6FhN7S7SlF7ekMIk8WUClRRdIm0EFvQ8c7CZC6ls4sUQgy6Ex-edTtjrFn393TnpxrHVSFSVKLcgtndlK67D-rLRwZwNazNmKMrZh-nEs6CJupt3udxN6WtWl9yRmO3kx7vdCqPB5S3WHXBuvJrpoQJ5SScVtK7BdYEgtrJBnETrPbHriBt3TU3Y2rGNC3gPm1gkR1ezRx06o9UlzI58UJ2pd0rbEJTaweJtMGeNL4NtTxoX-BJknShbX-l6Hj0WZ5_LVRD5BE_j-5VuABxPRMXXzzyWveDyse3MPWjAmNqjbRZ0XsOFoobwg6sVNJkRaqhpLPCACOkf0Uc2DgHE2wRa5zaeWjEPi9A_Sayf8m9jnKURsAuqvdeF9obp_1G00)

Hier ist die aktualisierte Variante. Ich lade sie sogleich auch noch ins Wiki hoch.

**Comment by Anasalzoabi** [comment]
Das wirkt einfacher und verständlicher.

**Comment by Supergecki** [comment]
Ich habe den Issue umbenannt, weil das grundsätzliche Klassendesign des Backends ja jetzt auf jeden Fall fertig ist. Da du vorhast, doch mit WFA statt Maui zu arbeiten, müssen hier noch Anpassungen im GUI-Klassendesign vorgenommen werden.

**Comment by Supergecki** [comment]
Dieser Issue ist jetzt noch wichtig @Anasalzoabi . Dadurch, dass du dich jetzt für WFA entschieden hast, habe ich keinen Überblick mehr über die Klassenstruktur, deswegen würde ich dir jetzt die Überarbeitung der Klassendiagramme überlassen.

**Comment by Anasalzoabi** [comment]
![pLRVRzis47xFNq5WBpPM6UYxQtIrqyoOimMDamKe2eEHhWvNYXH8AexNvN_VKQ95sTGefnxG-i4soVk--tG_Zdgh3LMcpFbPGTClT0raGPUAtItO_HAqqUJh6S5FogdMnExCgA4N841H8vKzTP-Vo7YCN8QbamdHHZ6n_lY964IiwfMkJ9_FMdmpMTvpkAHu_XJZJf1R0Ssau5jaNp1jnl](https://github.com/user-attachments/assets/ba7ea81d-48dc-48ac-924d-748d9736eb6d)

Das Design der Klassen und die Wahl der Technologie wurden sorgfältig durchdacht, um sicherzustellen, dass unser System modular, testbar und benutzerfreundlich ist. Die Entscheidung, das Programm mit dem WFA .NET Framework zu entwickeln, wurde nach Absprache mit Matin getroffen, da es eine einfachere und effizientere Lösung für unsere Anforderungen bietet als MAUI.
