### ISSUE TITLE
Dokumentationserstellungsworkflow: Dokumentation

### ISSUE THREAD

**Issue by Supergecki** [Supergecki/LaTriX#27]
Im Wiki auf der Seite "Repository-Workflows" (https://github.com/Supergecki/LaTriX/wiki/Repository%E2%80%90Workflows) befindet sich momentan nur die Beschreibung des Workflows für integrierte Builds und Testing. Eine kurze Beschreibung des Doxygen-Workflows wäre hier auch vonnöten, wieder mit den gleichen Unterpunkten (was es tut, warum es das tut, wie es getestet wurde, Konfiguration).

Diese Beschreibung kann auf dieselbe Wiki-Seite geschrieben werden, sollte aber durch eine neue Überschrift abgegrenzt werden. Einfügen des Badges wäre auch wieder gut.

**Comment by Anasalzoabi** [comment]
ist erledigt : )
