### ISSUE TITLE
Überflüssige Branches löschen

### ISSUE THREAD

**Issue by Supergecki** [Supergecki/LaTriX#30]
Die beiden Branches [Anasalzoabi-patch-1](https://github.com/Supergecki/LaTriX/tree/Anasalzoabi-patch-1) und [new-Branch](https://github.com/Supergecki/LaTriX/tree/new-Branch) wurden bereits mit der kombinierten Pull-Request #25 nach main überführt, enthalten also mittlerweile veraltete Datenstände. Wenn auf diesen Branches nicht mehr entwickelt wird, sollten sie gelöscht werden.

**Comment by Anasalzoabi** [comment]
ist erledigt :)
