### ISSUE TITLE
Automatische Dokumentationserstellung einrichten

### ISSUE THREAD

**Issue by Supergecki** [Supergecki/LaTriX#4]
Die Dokumentation des Codes sollte automatisch generiert werden. Hierfür würde sich bspw. Doxygen als Framework anbieten.

**Comment by Supergecki** [comment]
Gab es hierzu Fortschritte? Die Doxy-Comments sind ja jetzt alle aktiviert, also sollte diesem Issue nichts mehr im Wege stehen.

**Comment by Anasalzoabi** [comment]
Ich mach es heute fertig .

**Comment by Supergecki** [comment]
Es gibt gerade noch ein kleines Problem mit den Einstellungen des Repositories, es hat sich ein automatischer Workflow eingeschlichen, der fälschlicherweise den falschen Branch deployt. Ich kümmere mich darum.

**Comment by Supergecki** [comment]
Jetzt scheint es wieder zu funktionieren, gerne auf https://supergecki.github.io/LaTriX/index.html nochmal nachschauen.
